add rpath check to release ci for sparkle updates

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,21 +44,25 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
       - name: Install Rust toolchain
         uses: dtolnay/rust-toolchain@stable
         with:
           toolchain: ${{ matrix.toolchain }}
           target: ${{ matrix.target }}
+
       - name: Handle Rust dependencies caching
         uses: Swatinem/rust-cache@v2
         with:
           key: v1-${{ matrix.target }}
+
       - name: Build release binary
         uses: clechasseur/rs-cargo@v3
         with:
           command: build
           args: --release --target ${{ matrix.target }}
           tool: ${{ matrix.cargo-tool }}
+
       - name: Verify binary architecture
         shell: bash
         run: |
@@ -73,6 +77,7 @@ jobs:
             exit 1
           fi
           echo "ok: Architecture match"
+
       - name: Ensure binary successfully boots
         shell: bash
         run: |
@@ -88,6 +93,7 @@ jobs:
             *)
               ./$BINARY_PATH --version;;
           esac
+
       - name: Upload binary artifact
         uses: actions/upload-artifact@v4
         with:
@@ -119,11 +125,22 @@ jobs:
             x86_64-binary/edl-gen \
             arm64-binary/edl-gen
 
-      - name: Verify universal binary
+      - name: Ensure universal binary boots
         run: |
           chmod +x edl-gen
           lipo -info edl-gen
           ./edl-gen --version
+
+      - name: Veryify rpath for updates
+        run: |
+          RPATH_OUTPUT=$(otool -l edl-gen | grep -A 2 LC_RPATH)
+          if [ -z "$RPATH_OUTPUT" ]; then
+              echo "Error: RPATH is missing. Required for Sparkle update framework." >&2
+              exit 1
+          else
+              echo "RPATH is present:"
+              echo "$RPATH_OUTPUT"
+          fi
 
       - name: Upload universal binary
         uses: actions/upload-artifact@v4
@@ -161,3 +178,4 @@ jobs:
           command: make copied-site
           signing_key: ${{ secrets.SIGNING_KEY }}
           agree_to_license: 1
+
